version: '3.9'
services:
  app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - db1:/opt/app/database
    ports:
      - "8000:8000"
  tests:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    command: python3 manage.py test
volumes:
  db1:
