# Generated by Django 3.1.7 on 2021-03-31 22:01

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Football', '0001_initial_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballteam',
            name='country',
            field=django_countries.fields.CountryField(db_index=True, max_length=2),
        ),
    ]
