name: CI

on:
  push:
    branches:
      - 'master'

env:
  REGISTRY: public.ecr.aws/j3n5d8i7
  # github.repository as <account>/<repo>
  # IMAGE_NAME: ${{ github.repository }}
  IMAGE_NAME: drf-tailapp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        run: |
          docker-compose build

      - name: Run tests
        run: |
          docker-compose run tests

      - name: Log into registry ${{ env.REGISTRY }}
        run: |
          echo ${{ secrets.AWS_ECR_PASSWORD }} | docker login --username AWS --password-stdin ${{ env.REGISTRY }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
