name: CI

on:
  push:
    branches:
      - 'master'

env:
  REGISTRY: public.ecr.aws/j3n5d8i7
  # github.repository as <account>/<repo>
  # IMAGE_NAME: ${{ github.repository }}
  IMAGE_NAME: drf-tailapp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        run: |
          docker build -t drf-tailapp -f docker/Dockerfile .

      - name: Run tests
        run: |
          docker run \
            -e DATABASE_NAME=${{ secrets.DB_NAME }} \
            -e DATABASE_USER=${{ secrets.DB_USER }} \
            -e DATABASE_PASSWORD=${{ secrets.DB_PASS }} \
            -e DATABASE_HOST=${{ secrets.DB_HOST }} \
            drf-tailapp \
            python3 manage.py test

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        run: |
          aws ecr-public get-login-password --region us-east-1 \
            | docker login --username AWS --password-stdin ${{ env.REGISTRY }}

      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker tag drf-tailapp:latest ${{ env.REGISTRY }}/drf-tailapp:latest

      - name: Log out of Amazon ECR
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}
