name: CI

on:
  push:
    branches:
      - 'master'

env:
  REGISTRY: public.ecr.aws/j3n5d8i7
  # github.repository as <account>/<repo>
  # IMAGE_NAME: ${{ github.repository }}
  IMAGE_NAME: drf-tailapp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        run: |
          docker build -t drf-tailapp -f docker/Dockerfile .

      - name: Run tests
        run: |
          docker run \
            -e DATABASE_NAME=${{ secrets.DB_NAME }} \
            -e DATABASE_USER=${{ secrets.DB_USER }} \
            -e DATABASE_PASSWORD=${{ secrets.DB_PASS }} \
            -e DATABASE_HOST=${{ secrets.DB_HOST }} \
            drf-tailapp \
            python3 manage.py test

      - name: Log into registry ${{ env.REGISTRY }}
        run: |
          echo ${{ secrets.AWS_ECR_PASSWORD }} | docker login --username AWS --password-stdin ${{ env.REGISTRY }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
